version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: db_ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - C:\docker\postgres\login:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  ecommerce:
